### ISSUE TITLE
Bug in `area_statistics` preprocessor: `AttributeError: 'str' object has no attribute 'ndim'`

### ISSUE THREAD

**Issue by ehogan** [ESMValGroup/ESMValCore#2208]
**Describe the bug**
I was looking at a RTW issue today, but when I run the current version of the RTW (which uses the latest versions i.e. `main` of ESMValCore and ESMValTool), the [radiation budget recipe](https://github.com/ESMValGroup/ESMValTool/blob/main/esmvaltool/recipes/recipe_radiation_budget.yml) fails with the error:

```
  File "/latest/ESMValCore/esmvalcore/preprocessor/_area.py", line 397, in area_statistics
    result = cube.collapsed(coord_names, operation, weights='cell_area')
  File "/environments/esmvaltool-2.8.0/lib/python3.10/site-packages/iris/cube.py", line 3936, in collapsed
    if weights is not None and weights.ndim > 1:
AttributeError: 'str' object has no attribute 'ndim'
```

I can confirm that the radiation budget recipe passes using ESMValTool v2.9.0.

The change to L397 in `ESMValCore/esmvalcore/preprocessor/_area.py` was introduced in #2139, after the v2.9.0 release.

@schlunma, @valeriupredoi, tagging you both since you developed and reviewed #2139, respectively; would either of you know how to fix this quickly? Otherwise I can look more closely at it :)

**Comment by schlunma** [comment]
Have you updated iris to the latest version? This exact error appears when using an old iris version (I believe <3.5).

**Comment by ehogan** [comment]
Ah, thanks @schlunma, that's exactly it; I'm using an old v2.9.0 environment that contains Iris v3.4.1. I will try with a more recent version of Iris and I'll go ahead and close this issue :)
