### PR TITLE
Fix documentation

### PR DESCRIPTION
**Pull request by jvegasbsc**
Documentation is currently broken when using Sphinx 3.4. This pull request is meant to fix it

***

## Before you get started

-   \[ \] [☝ Create an issue](https://github.com/ESMValGroup/ESMValCore/issues) to discuss what you are going to do

## Checklist

-   \[ \] PR has a descriptive title for the [changelog](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] Code follows the [style guide](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#code-style)
-   \[ \] [Documentation](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#documentation) is available for new functionality
-   \[ \] YAML files pass [`pre-commit`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#pre-commit) or [`yamllint`](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/community/introduction.html#yaml) checks
-   \[ \] [Circle/CI tests pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] [Codacy code quality checks pass](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review)
-   \[ \] [Documentation builds successfully](https://docs.esmvaltool.org/projects/esmvalcore/en/latest/contributing.html#branches-pull-requests-and-code-review) on readthedocs
-   \[ \] [Unit tests](https://docs.esmvaltool.org/projects/esmvalcore/projects/esmvalcore/en/latest/contributing.html#contributing-to-the-esmvalcore-package) are available

If you make backwards incompatible changes to the recipe format:

-   \[ \] Update [ESMValTool](https://github.com/esmvalgroup/esmvaltool) and link the pull request(s) in the description

***

To help with the number pull requests:

-   🙏 We kindly ask you to [review](https://docs.esmvaltool.org/en/latest/community/review.html#review-of-pull-requests) two other [open pull requests](https://github.com/ESMValGroup/ESMValTool/pulls) in this repository

### CODE REVIEW

**Comment by jvegasbsc** [comment]
I also needed to add the :noindex: tag to the automodules in 'api.preprocessor'

**Comment by zklaus** [comment]
This seems to be a stop-gap measure. What is the obstruction to making it work with Sphinx 3.4 and why can we not overcome that?

**Comment by jvegasbsc** [comment]
> This seems to be a stop-gap measure. What is the obstruction to making it work with Sphinx 3.4 and why can we not overcome that?

There is a problem with the automodule and the new 'Config' class:

```
Exception occurred:
  File "/opt/conda/lib/python3.8/site-packages/sphinx/util/typing.py", line 158, in _restify_py37
    return ':obj:`%s.%s`' % (cls.__module__, cls.__name__)
AttributeError: 'Config' object has no attribute '__name__'
```
It seems that it is getting an object when the code is expecting a class. I do not understand well why this is happening, or if this is even our fault or sphinx's. I decided to do a quick fix to the documentation to make it work and at least get rid of all false errors we have now in every pull request.

I can create an issue about documentation not working with sphinx 3.4.0 so we do not forget about this

**Comment by stefsmeets** [comment]
> 
> 
> This seems to be a stop-gap measure. What is the obstruction to making it work with Sphinx 3.4 and why can we not overcome that?

I agree with this. Should be straightforward to make it work with 3.4 rather than pin it on 3.3.

**Comment by bouweandela** [comment]
Surprisingly the documentation is building just fine in #921 with Sphinx==3.4.2, so I wonder if these changes are still needed?

**Comment by jvegasbsc** [comment]
>  or if this is even our fault or sphinx's.

It looks like it was Sphinx's fault, after all...
